// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 16.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4CAGC.Template
{
    using System.Collections.Generic;
    using T4CAGC.Model;
    using T4CAGC.Extension;
    using Microservice.Library.Extension;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Controller : ControllerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("  \r\n");
            this.Write(@"/*\__________________________________________________________________________________________________
|*												提示											 __≣|
|* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~| 
|*      此代码由T4模板自动生成																	|
|*		版本:");
            
            #line 6 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\.\Reuseable\BaseHead.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Version.PadRight(83, ' ')));
            
            #line default
            #line hidden
            this.Write("|__\r\n|*\t\t日期:");
            
            #line 7 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\.\Reuseable\BaseHead.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss").PadRight(86, ' ')));
            
            #line default
            #line hidden
            this.Write("≣|\r\n|*\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tby  LCTR\t\t   ≣|\r\n|* ___________________________________" +
                    "_____________________________________________________________≣|\r\n\\*/\r\n");
            
            #line 11 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\.\Reuseable\BaseHead.ttinclude"

	foreach (var @namespace in NameSpaces?.OrderBy(o => o))
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 15 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\.\Reuseable\BaseHead.ttinclude"
            this.Write(this.ToStringHelper.ToStringWithCulture(@namespace));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 16 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\.\Reuseable\BaseHead.ttinclude"

	}

            
            #line default
            #line hidden
            this.Write("\r\nnamespace Api.Controllers\r\n{\r\n    /// <summary>\r\n    /// ");
            
            #line 11 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.Remark));
            
            #line default
            #line hidden
            this.Write("接口\r\n    /// </summary>\r\n    [Route(\"/");
            
            #line 13 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.Name.GetAbbreviation(30).ToLower()));
            
            #line default
            #line hidden
            this.Write("\")]\r\n    [SampleAuthorize(nameof(ApiAuthorizeRequirement))]\r\n    [SwaggerTag(\"");
            
            #line 15 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.Remark));
            
            #line default
            #line hidden
            this.Write("接口\")]\r\n    public class ");
            
            #line 16 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Controller : BaseApiController\r\n    {\r\n        #region DI\r\n\r\n        /// <summary" +
                    ">\r\n        /// \r\n        /// </summary>\r\n        /// <param name=\"");
            
            #line 23 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Business\"></param>\r\n        public SampleController(I");
            
            #line 24 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business ");
            
            #line 24 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Business)\r\n        {\r\n            ");
            
            #line 26 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business = ");
            
            #line 26 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Business;\r\n        }\r\n\r\n        /// <summary>\r\n        /// ");
            
            #line 30 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.Remark));
            
            #line default
            #line hidden
            this.Write("接口类\r\n        /// </summary>\r\n        readonly I");
            
            #line 32 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business ");
            
            #line 32 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business;\r\n\r\n        #endregion\r\n\r\n        #region 基础功能\r\n\r\n");
            
            #line 38 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    foreach (var field in Options.Table.Fields)
    {
        if(field.Consts.Any_Ex())
        {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// 获取");
            
            #line 46 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Remark));
            
            #line default
            #line hidden
            this.Write("集合\r\n        /// </summary>\r\n        /// <returns></returns>\r\n        [HttpPost(\"");
            
            #line 49 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("-list\")]\r\n        [SwaggerResponse((int)HttpStatusCode.OK, \"");
            
            #line 50 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Remark));
            
            #line default
            #line hidden
            this.Write("\", typeof(List<string>))]\r\n        public async Task<object> Get");
            
            #line 51 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("List()\r\n        {\r\n            return await Task.FromResult(Success(");
            
            #line 53 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.Get");
            
            #line 53 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("List()));\r\n        }\r\n");
            
            #line 55 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

        }
        
        if(field.Enums.Any_Ex())
        {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// 获取");
            
            #line 63 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Remark));
            
            #line default
            #line hidden
            this.Write("字典\r\n        /// </summary>\r\n        /// <returns></returns>\r\n        [HttpPost(\"");
            
            #line 66 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("-dic\")]\r\n        [SwaggerResponse((int)HttpStatusCode.OK, \"");
            
            #line 67 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Remark));
            
            #line default
            #line hidden
            this.Write("\", typeof(Dictionary<string, int>))]\r\n        public async Task<object> Get");
            
            #line 68 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("Dic()\r\n        {\r\n            return await Task.FromResult(Success(");
            
            #line 70 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.Get");
            
            #line 70 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write("Dic()));\r\n        }\r\n");
            
            #line 72 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

        }
    }

    if(Functions.ContainsKey(Function.List))
    {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// 获取列表数据\r\n        /// </summary>\r\n        /// " +
                    "<param name=\"pagination\">分页设置</param>\r\n        /// <returns></returns>\r\n        " +
                    "[HttpPost(\"list\")]\r\n        [SwaggerResponse((int)HttpStatusCode.OK, \"列表数据\", typ" +
                    "eof(");
            
            #line 86 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Functions[Function.List]));
            
            #line default
            #line hidden
            this.Write("))]\r\n        public async Task<object> GetList([FromBody] PaginationDTO paginatio" +
                    "n)\r\n        {\r\n            return await Task.FromResult(OpenApiJsonContent(");
            
            #line 89 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.GetList(pagination), pagination));\r\n        }\r\n");
            
            #line 91 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }

    if(Functions.ContainsKey(Function.Detail))
    {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// 详情数据数据\r\n        /// </summary>\r\n");
            
            #line 101 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryParamsRemark();
            
            #line default
            #line hidden
            this.Write("        /// <returns></returns>\r\n        [HttpPost(\"detail-data");
            
            #line 103 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryRouteParams();
            
            #line default
            #line hidden
            this.Write("\")]\r\n        [SwaggerResponse((int)HttpStatusCode.OK, \"详情数据\", typeof(");
            
            #line 104 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Functions[Function.Detail]));
            
            #line default
            #line hidden
            this.Write("))]\r\n        public async Task<object> GetDetail(");
            
            #line 105 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryParams();
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return await Task.FromResult(OpenApiJsonContent(Respons" +
                    "eDataFactory.Success(");
            
            #line 107 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.GetDetail(");
            
            #line 107 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryMethodParams();
            
            #line default
            #line hidden
            this.Write("))));\r\n        }\r\n");
            
            #line 109 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }

    if(Functions.ContainsKey(Function.Create))
    {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// 新增\r\n        /// </summary>\r\n        /// <par" +
                    "am name=\"data\">表单数据</param>\r\n        /// <returns></returns>\r\n        [HttpPost(" +
                    "\"create\")]\r\n        public async Task<object> Create([FromBody] ");
            
            #line 122 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Functions[Function.Create]));
            
            #line default
            #line hidden
            this.Write(" data)\r\n        {\r\n            ");
            
            #line 124 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.Create(data);\r\n            return await Task.FromResult(Success(\"添加成功.\")" +
                    ");\r\n        }\r\n");
            
            #line 127 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }

    if(Functions.ContainsKey(Function.Edit))
    {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// 获取编辑数据\r\n        /// </summary>\r\n");
            
            #line 137 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryParamsRemark();
            
            #line default
            #line hidden
            this.Write("        /// <returns></returns>\r\n        [HttpPost(\"edit-data");
            
            #line 139 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryRouteParams();
            
            #line default
            #line hidden
            this.Write("\")]\r\n        [SwaggerResponse((int)HttpStatusCode.OK, \"编辑数据\", typeof(");
            
            #line 140 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Functions[Function.Edit]));
            
            #line default
            #line hidden
            this.Write("))]\r\n        public async Task<object> GetEdit(");
            
            #line 141 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryParams();
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return await Task.FromResult(OpenApiJsonContent(Respons" +
                    "eDataFactory.Success(");
            
            #line 143 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.GetEdit(");
            
            #line 143 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryMethodParams();
            
            #line default
            #line hidden
            this.Write("))));\r\n        }\r\n\r\n        /// <summary>\r\n        /// 编辑数据\r\n        /// </summar" +
                    "y>\r\n        /// <param name=\"data\">表单数据</param>\r\n        /// <returns></returns>" +
                    "\r\n        [HttpPost(\"edit\")]\r\n        public async Task<object> Edit([FromBody] " +
                    "");
            
            #line 152 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Functions[Function.Edit]));
            
            #line default
            #line hidden
            this.Write(" data)\r\n        {\r\n            ");
            
            #line 154 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.Edit(data);\r\n            return await Task.FromResult(Success());\r\n     " +
                    "   }\r\n");
            
            #line 157 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }

    if(Functions.ContainsKey(Function.Delete))
    {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// 删除数据\r\n        /// </summary>\r\n");
            
            #line 167 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryListParamsRemark();
            
            #line default
            #line hidden
            this.Write("        /// <returns></returns>\r\n        [HttpPost(\"delete\")]\r\n        public asy" +
                    "nc Task<object> Delete(IEnumerable<string> keys)\r\n        {\r\n            ");
            
            #line 172 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.Delete(keys?.ToList());\r\n            return await Task.FromResult(Succes" +
                    "s());\r\n        }\r\n");
            
            #line 175 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        #endregion\r\n\r\n        #region 拓展功能\r\n");
            
            #line 182 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    if(Functions.ContainsKey(Function.Enable))
    {

            
            #line default
            #line hidden
            this.Write("\r\n        /// <summary>\r\n        /// 启用/禁用\r\n        /// </summary>\r\n");
            
            #line 190 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryParamsRemark();
            
            #line default
            #line hidden
            this.Write("        /// <param name=\"enable\">设置状态</param>\r\n        /// <returns></returns>\r\n " +
                    "       [HttpPost(\"enable");
            
            #line 193 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryRouteParams();
            
            #line default
            #line hidden
            this.Write("/{enable}\")]\r\n        public async Task<object> Enable(");
            
            #line 194 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryParams();
            
            #line default
            #line hidden
            this.Write(", bool enable)\r\n        {\r\n            ");
            
            #line 196 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.Enable(");
            
            #line 196 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
WritePrimaryMethodParams();
            
            #line default
            #line hidden
            this.Write(", enable);\r\n            return await Task.FromResult(Success());\r\n        }\r\n");
            
            #line 199 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }
    
    if(Functions.ContainsKey(Function.Sort))
    {

            
            #line default
            #line hidden
            this.Write(@"
        /// <summary>
        /// 普通排序
        /// </summary>
        /// <param name=""data"">数据</param>
        /// <returns></returns>
        [HttpPost(""sort"")]
        public async Task<object> Sort([FromBody] Sort data)
        {
            ");
            
            #line 214 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write(@"Business.Sort(data);
            return await Task.FromResult(Success());
        }

        /// <summary>
        /// 拖动排序
        /// </summary>
        /// <param name=""data"">数据</param>
        /// <returns></returns>
        [HttpPost(""dragsort"")]
        public async Task<object> DragSort([FromBody] ");
            
            #line 224 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.Tree ? "TreeDragSort" : "DragSort"));
            
            #line default
            #line hidden
            this.Write(" data)\r\n        {\r\n            ");
            
            #line 226 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.DragSort(data);\r\n            return await Task.FromResult(Success());\r\n " +
                    "       }\r\n");
            
            #line 229 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }
    
    if(Functions.ContainsKey(Function.Import))
    {

            
            #line default
            #line hidden
            this.Write(@"
        /// <summary>
        /// 下载导入模板
        /// </summary>
        /// <param name=""version"">
        /// <para>指定Excel文件版本</para>
        /// <para><see cref=""ExcelVersion.xls""/>: 2003版本</para>
        /// <para>(默认)<see cref=""ExcelVersion.xlsx""/>: 2007及以上版本</para>
        /// </param>
        /// <param name=""autogenerateTemplate"">
        /// <para>指明要使用的模板类型</para>
        /// <para>true: 自动生成模板</para>
        /// <para>(默认)false: 使用预制模板</para>
        /// </param>
        /// <returns></returns>
        [HttpGet(""downloadtemplate"")]
        public async Task DownloadTemplate(string version = ExcelVersion.xlsx, bool autogenerateTemplate = false)
        {
            await ");
            
            #line 253 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write(@"Business.DownloadTemplate(version, autogenerateTemplate);
        }

        /// <summary>
        /// 导入
        /// </summary>
        /// <param name=""file"">Execl文件</param>
        /// <param name=""autogenerateTemplate"">
        /// <para>指明所使用的模板类型</para>
        /// <para>true: 自动生成的模板</para>
        /// <para>(默认)false: 预制模板</para>
        /// </param>
        /// <returns></returns>
        [HttpPost(""import"")]
        [SwaggerResponse((int)HttpStatusCode.OK, ""导入结果"", typeof(ImportResult))]
        [Consumes(""multipart/form-data"")]
        public async Task<object> Import(IFormFile file, bool autogenerateTemplate = false)
        {
            return await Task.FromResult(ResponseDataFactory.Success(");
            
            #line 271 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.Import(file, autogenerateTemplate)));\r\n        }\r\n");
            
            #line 273 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }
    
    if(Functions.ContainsKey(Function.Export))
    {

            
            #line default
            #line hidden
            this.Write(@"
        /// <summary>
        /// 导出
        /// </summary>
        /// <param name=""version"">
        /// <para>指定Excel文件版本</para>
        /// <para><see cref=""ExcelVersion.xls""/>: 2003版本</para>
        /// <para>(默认)<see cref=""ExcelVersion.xlsx""/>: 2007及以上版本</para>
        /// </param>
        /// <param name=""paginationJson"">分页参数Json字符串</param>
        /// <returns></returns>
        [HttpGet(""export"")]
        public void Export(string version = ExcelVersion.xlsx, string paginationJson = null)
        {
            ");
            
            #line 293 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Options.Table.ReducedName));
            
            #line default
            #line hidden
            this.Write("Business.Export(version, paginationJson);\r\n        }\r\n");
            
            #line 295 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        #endregion\r\n    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 303 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    /// <summary>
    /// 主键参数注释
    /// </summary>
    private void WritePrimaryParamsRemark()
    {
        foreach (var field in PrimaryKeys)
        {

        
        #line default
        #line hidden
        
        #line 311 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("        /// <param name=\"");

        
        #line default
        #line hidden
        
        #line 312 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToLower()));

        
        #line default
        #line hidden
        
        #line 312 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("\">");

        
        #line default
        #line hidden
        
        #line 312 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Remark));

        
        #line default
        #line hidden
        
        #line 312 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("</param>\r\n");

        
        #line default
        #line hidden
        
        #line 313 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

        }
    }

    /// <summary>
    /// 主键参数
    /// </summary>
    private void WritePrimaryParams()
    {
        var i = 0;
        foreach (var field in PrimaryKeys)
        {

        
        #line default
        #line hidden
        
        #line 325 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(i > 0 ? ", " : ""));

        
        #line default
        #line hidden
        
        #line 325 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Type));

        
        #line default
        #line hidden
        
        #line 325 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(" ");

        
        #line default
        #line hidden
        
        #line 325 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToLower()));

        
        #line default
        #line hidden
        
        #line 325 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

            i++;
        }
    }

    /// <summary>
    /// 主键路由参数
    /// </summary>
    private void WritePrimaryRouteParams()
    {
        foreach (var field in PrimaryKeys)
        {

        
        #line default
        #line hidden
        
        #line 337 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("/{");

        
        #line default
        #line hidden
        
        #line 337 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToLower()));

        
        #line default
        #line hidden
        
        #line 337 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("}");

        
        #line default
        #line hidden
        
        #line 337 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

        }
    }

    /// <summary>
    /// 主键方法参数
    /// </summary>
    private void WritePrimaryMethodParams()
    {
        var i = 0;
        foreach (var field in PrimaryKeys)
        {

        
        #line default
        #line hidden
        
        #line 349 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(i > 0 ? ", " : ""));

        
        #line default
        #line hidden
        
        #line 349 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Name.ToLower()));

        
        #line default
        #line hidden
        
        #line 349 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

            i++;
        }
    }

    /// <summary>
    /// 主键集合参数注释
    /// </summary>
    private void WritePrimaryListParamsRemark()
    {

        
        #line default
        #line hidden
        
        #line 359 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("/// <param name=\"keys\">");

        
        #line default
        #line hidden
        
        #line 359 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

        var i = 0;
        foreach (var field in PrimaryKeys)
        {

        
        #line default
        #line hidden
        
        #line 363 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("[[");

        
        #line default
        #line hidden
        
        #line 363 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(i > 0 ? " + " : ""));

        
        #line default
        #line hidden
        
        #line 363 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(field.Remark));

        
        #line default
        #line hidden
        
        #line 363 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("]]");

        
        #line default
        #line hidden
        
        #line 363 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

            i++;
        }

        
        #line default
        #line hidden
        
        #line 366 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"
this.Write("</param>");

        
        #line default
        #line hidden
        
        #line 366 "F:\图锐信息\项目框架学习\GitHub社区项目\Microservice\src\Tools\T4CAGC\Template\Controller.tt"

    }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ControllerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
